version: "3.0"
services:
    frontend:
        build: ./frontend
        volumes:
            - ./frontend/htdocs:/usr/local/apache2/htdocs
        ports:
            - 80:80

    backend:
        build: ./backend
        volumes:
            - ./backend/src:/app
        ports:
            - 3000:3000
